# Generated by Django 3.2.6 on 2021-08-17 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, default=0, max_digits=65)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_activity_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('units', models.CharField(choices=[('0', 'čtvereční metr'), ('1', 'jednota')], default='0', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculaber_app.generateduser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_pic', models.ImageField(blank=True, upload_to='project_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculaber_app.generateduser')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculaber_app.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculaber_app.project')),
            ],
        ),
    ]
