# Generated by Django 3.2.6 on 2021-09-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0003_auto_20210907_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='calculaber_app.project'),
            preserve_default=False,
        ),
    ]
