# Generated by Django 3.2.6 on 2021-09-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0004_material_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='project',
        ),
    ]
