# Generated by Django 3.2.6 on 2021-09-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0007_alter_material_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialobject',
            name='name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
