# Generated by Django 3.2.6 on 2021-09-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0008_materialobject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='project',
        ),
    ]
