# Generated by Django 3.2.6 on 2021-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0010_auto_20210914_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialobject',
            name='customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialobject',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='materialobject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
    ]
