# Generated by Django 3.2.6 on 2021-10-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0013_auto_20210930_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
        migrations.AlterField(
            model_name='materialobject',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
    ]
