# Generated by Django 3.2.6 on 2021-10-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0014_auto_20211005_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='units',
            field=models.CharField(choices=[('0', 'kus'), ('1', 'm2'), ('2', 'm3'), ('3', 'm'), ('4', 'cm'), ('5', 'mm')], default='0', max_length=2),
        ),
    ]
