# Generated by Django 3.2.6 on 2021-10-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0017_extraexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraexpense',
            name='name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
