# Generated by Django 3.2.6 on 2021-11-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0020_alter_materialtag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtag',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
