# Generated by Django 3.2.6 on 2021-11-29 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculaber_app', '0022_alter_materialtag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculaber_app.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
