# Generated by Django 3.2.6 on 2021-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculaber_app', '0023_objecttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, default='project_pics/default.png', upload_to='project_pics'),
        ),
    ]
